// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/geeter/geeter.proto

package geeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Geeter service

func NewGeeterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Geeter service

type GeeterService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Geeter_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Geeter_PingPongService, error)
}

type geeterService struct {
	c    client.Client
	name string
}

func NewGeeterService(name string, c client.Client) GeeterService {
	return &geeterService{
		c:    c,
		name: name,
	}
}

func (c *geeterService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Geeter.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geeterService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Geeter_StreamService, error) {
	req := c.c.NewRequest(c.name, "Geeter.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &geeterServiceStream{stream}, nil
}

type Geeter_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type geeterServiceStream struct {
	stream client.Stream
}

func (x *geeterServiceStream) Close() error {
	return x.stream.Close()
}

func (x *geeterServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *geeterServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *geeterServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *geeterServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *geeterService) PingPong(ctx context.Context, opts ...client.CallOption) (Geeter_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Geeter.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &geeterServicePingPong{stream}, nil
}

type Geeter_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type geeterServicePingPong struct {
	stream client.Stream
}

func (x *geeterServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *geeterServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *geeterServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *geeterServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *geeterServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *geeterServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Geeter service

type GeeterHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Geeter_StreamStream) error
	PingPong(context.Context, Geeter_PingPongStream) error
}

func RegisterGeeterHandler(s server.Server, hdlr GeeterHandler, opts ...server.HandlerOption) error {
	type geeter interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Geeter struct {
		geeter
	}
	h := &geeterHandler{hdlr}
	return s.Handle(s.NewHandler(&Geeter{h}, opts...))
}

type geeterHandler struct {
	GeeterHandler
}

func (h *geeterHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GeeterHandler.Call(ctx, in, out)
}

func (h *geeterHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GeeterHandler.Stream(ctx, m, &geeterStreamStream{stream})
}

type Geeter_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type geeterStreamStream struct {
	stream server.Stream
}

func (x *geeterStreamStream) Close() error {
	return x.stream.Close()
}

func (x *geeterStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *geeterStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *geeterStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *geeterStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *geeterHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GeeterHandler.PingPong(ctx, &geeterPingPongStream{stream})
}

type Geeter_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type geeterPingPongStream struct {
	stream server.Stream
}

func (x *geeterPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *geeterPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *geeterPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *geeterPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *geeterPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *geeterPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
